---
# CSIDriver resource
apiVersion: storage.k8s.io/v1
kind: CSIDriver
metadata:
  name: tns.csi.io
spec:
  # Supports persistent volumes
  attachRequired: false
  podInfoOnMount: false
  # Volume lifecycle modes
  volumeLifecycleModes:
    - Persistent
